
import builder from '@builder';
import { Prisma } from '.prisma/client';
export {
  PushTokenObject,
  PushTokenIdFieldObject,
  PushTokenIsExpiredFieldObject,
  PushTokenExpoTokenFieldObject,
  PushTokenAndroidTokenFieldObject,
  PushTokenAppleTokenFieldObject,
  PushTokenDeviceFieldObject,
  PushTokenReceiptsFieldObject,
  PushTokenCreatedAtFieldObject,
  PushTokenUpdatedAtFieldObject,
  createManyPushTokenMutation,
  createOnePushTokenMutation,
  deleteManyPushTokenMutation,
  deleteOnePushTokenMutation,
  updateManyPushTokenMutation,
  updateOnePushTokenMutation,
  upsertOnePushTokenMutation,
  createManyPushTokenMutationObject,
  createOnePushTokenMutationObject,
  deleteManyPushTokenMutationObject,
  deleteOnePushTokenMutationObject,
  updateManyPushTokenMutationObject,
  updateOnePushTokenMutationObject,
  upsertOnePushTokenMutationObject,
  findFirstPushTokenQuery,
  findManyPushTokenQuery,
  countPushTokenQuery,
  findUniquePushTokenQuery,
  findFirstPushTokenQueryObject,
  findManyPushTokenQueryObject,
  countPushTokenQueryObject,
  findUniquePushTokenQueryObject
} from './PushToken';
export {
  DeviceObject,
  DeviceIdFieldObject,
  DeviceDeviceTypeFieldObject,
  DeviceDeviceManagerFieldObject,
  DeviceDeviceManagerIdFieldObject,
  DevicePushTokenFieldObject,
  DevicePushTokenIdFieldObject,
  DeviceCreatedAtFieldObject,
  DeviceUpdatedAtFieldObject,
  createManyDeviceMutation,
  createOneDeviceMutation,
  deleteManyDeviceMutation,
  deleteOneDeviceMutation,
  updateManyDeviceMutation,
  updateOneDeviceMutation,
  upsertOneDeviceMutation,
  createManyDeviceMutationObject,
  createOneDeviceMutationObject,
  deleteManyDeviceMutationObject,
  deleteOneDeviceMutationObject,
  updateManyDeviceMutationObject,
  updateOneDeviceMutationObject,
  upsertOneDeviceMutationObject,
  findFirstDeviceQuery,
  findManyDeviceQuery,
  countDeviceQuery,
  findUniqueDeviceQuery,
  findFirstDeviceQueryObject,
  findManyDeviceQueryObject,
  countDeviceQueryObject,
  findUniqueDeviceQueryObject
} from './Device';
export {
  DeviceManagerObject,
  DeviceManagerIdFieldObject,
  DeviceManagerDeviceFieldObject,
  DeviceManagerDeviceProfileFieldObject,
  DeviceManagerCreatedAtFieldObject,
  DeviceManagerUpdatedAtFieldObject,
  createManyDeviceManagerMutation,
  createOneDeviceManagerMutation,
  deleteManyDeviceManagerMutation,
  deleteOneDeviceManagerMutation,
  updateManyDeviceManagerMutation,
  updateOneDeviceManagerMutation,
  upsertOneDeviceManagerMutation,
  createManyDeviceManagerMutationObject,
  createOneDeviceManagerMutationObject,
  deleteManyDeviceManagerMutationObject,
  deleteOneDeviceManagerMutationObject,
  updateManyDeviceManagerMutationObject,
  updateOneDeviceManagerMutationObject,
  upsertOneDeviceManagerMutationObject,
  findFirstDeviceManagerQuery,
  findManyDeviceManagerQuery,
  countDeviceManagerQuery,
  findUniqueDeviceManagerQuery,
  findFirstDeviceManagerQueryObject,
  findManyDeviceManagerQueryObject,
  countDeviceManagerQueryObject,
  findUniqueDeviceManagerQueryObject
} from './DeviceManager';
export {
  DeviceProfileObject,
  DeviceProfileIdFieldObject,
  DeviceProfileAppTypeFieldObject,
  DeviceProfileProfileTypeFieldObject,
  DeviceProfileProfileIdFieldObject,
  DeviceProfileIsActiveFieldObject,
  DeviceProfileDeviceManagerFieldObject,
  DeviceProfileAccesstokenFieldObject,
  DeviceProfileRefreshTokenFieldObject,
  DeviceProfileDeviceManagerIdFieldObject,
  DeviceProfileCreatedAtFieldObject,
  DeviceProfileUpdatedAtFieldObject,
  createManyDeviceProfileMutation,
  createOneDeviceProfileMutation,
  deleteManyDeviceProfileMutation,
  deleteOneDeviceProfileMutation,
  updateManyDeviceProfileMutation,
  updateOneDeviceProfileMutation,
  upsertOneDeviceProfileMutation,
  createManyDeviceProfileMutationObject,
  createOneDeviceProfileMutationObject,
  deleteManyDeviceProfileMutationObject,
  deleteOneDeviceProfileMutationObject,
  updateManyDeviceProfileMutationObject,
  updateOneDeviceProfileMutationObject,
  upsertOneDeviceProfileMutationObject,
  findFirstDeviceProfileQuery,
  findManyDeviceProfileQuery,
  countDeviceProfileQuery,
  findUniqueDeviceProfileQuery,
  findFirstDeviceProfileQueryObject,
  findManyDeviceProfileQueryObject,
  countDeviceProfileQueryObject,
  findUniqueDeviceProfileQueryObject
} from './DeviceProfile';
export {
  RefreshTokenObject,
  RefreshTokenIdFieldObject,
  RefreshTokenTokenFieldObject,
  RefreshTokenDeviceProfileFieldObject,
  RefreshTokenDeviceProfileIdFieldObject,
  RefreshTokenCreatedAtFieldObject,
  RefreshTokenUpdatedAtFieldObject,
  createManyRefreshTokenMutation,
  createOneRefreshTokenMutation,
  deleteManyRefreshTokenMutation,
  deleteOneRefreshTokenMutation,
  updateManyRefreshTokenMutation,
  updateOneRefreshTokenMutation,
  upsertOneRefreshTokenMutation,
  createManyRefreshTokenMutationObject,
  createOneRefreshTokenMutationObject,
  deleteManyRefreshTokenMutationObject,
  deleteOneRefreshTokenMutationObject,
  updateManyRefreshTokenMutationObject,
  updateOneRefreshTokenMutationObject,
  upsertOneRefreshTokenMutationObject,
  findFirstRefreshTokenQuery,
  findManyRefreshTokenQuery,
  countRefreshTokenQuery,
  findUniqueRefreshTokenQuery,
  findFirstRefreshTokenQueryObject,
  findManyRefreshTokenQueryObject,
  countRefreshTokenQueryObject,
  findUniqueRefreshTokenQueryObject
} from './RefreshToken';

export const BatchPayload = builder.objectType(builder.objectRef<Prisma.BatchPayload>('BatchPayload'), {
  description: 'Batch payloads from prisma.',
  fields: (t) => ({
    count: t.exposeInt('count', { description: 'Prisma Batch Payload', nullable: false }),
  }),
});

export const modelNames = [
  'PushToken',
  'Device',
  'DeviceManager',
  'DeviceProfile',
  'RefreshToken',
] as const;

export type Model = typeof modelNames[number];
